# Generated by Django 5.0.6 on 2024-06-25 17:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TodoTask",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                (
                    "description",
                    models.CharField(default="description", max_length=255),
                ),
                ("due_date", models.DateField(default=datetime.date(2024, 6, 25))),
                ("completed", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "todo_task",
                "managed": True,
            },
        ),
    ]
