# Generated by Django 5.0.6 on 2024-06-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='amount',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(default='sample', max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='subcategory',
            field=models.CharField(default='sample_text', max_length=255),
        ),
    ]
