# Generated by Django 5.0.6 on 2024-06-30 19:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todotask',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
