# Generated by Django 5.0.6 on 2024-07-01 12:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_todotask_due_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todotask",
            name="due_date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
