# Generated by Django 5.0.6 on 2024-06-01 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_performancemusswessels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancemusswessels',
            name='filiale',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='performancemusswessels',
            name='kundenanzahl',
            field=models.BigIntegerField(),
        ),
    ]
