# Generated by Django 5.0.6 on 2024-06-02 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_performancemusswessels_filiale_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='performancemusswessels',
            table='performance_musswessels',
        ),
    ]
