# Generated by Django 5.0.6 on 2024-06-02 13:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_alter_performancemusswessels_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="performancemusswessels",
            table="performance_musswessels_new",
        ),
    ]
