# Generated by Django 5.0.6 on 2024-06-02 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_performancemusswessels_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='performancemusswessels',
            options={'managed': False},
        ),
    ]
