# Generated by Django 5.0.6 on 2024-06-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_alter_performancemusswessels_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="TodoTask",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("titel", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
                ("assignee", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "todo_task",
                "managed": True,
            },
        ),
        migrations.AlterModelOptions(
            name="performancemusswessels",
            options={"managed": True},
        ),
    ]
