# Generated by Django 5.0.6 on 2024-06-02 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_todotask_alter_performancemusswessels_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="performancemusswessels",
            name="datum",
            field=models.TextField(blank=True, db_column="Datum", null=True),
        ),
        migrations.AlterField(
            model_name="performancemusswessels",
            name="filiale",
            field=models.BigIntegerField(blank=True, db_column="Filiale", null=True),
        ),
        migrations.AlterField(
            model_name="performancemusswessels",
            name="id",
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="performancemusswessels",
            name="kundenanzahl",
            field=models.BigIntegerField(
                blank=True, db_column="Kundenanzahl", null=True
            ),
        ),
        migrations.AlterField(
            model_name="performancemusswessels",
            name="prodstunden",
            field=models.FloatField(blank=True, db_column="Prodstunden", null=True),
        ),
        migrations.AlterField(
            model_name="performancemusswessels",
            name="umsatz",
            field=models.FloatField(blank=True, db_column="Umsatz", null=True),
        ),
        migrations.AlterField(
            model_name="todotask",
            name="assignee",
            field=models.CharField(default="me", max_length=255),
        ),
        migrations.AlterField(
            model_name="todotask",
            name="description",
            field=models.CharField(default="description", max_length=255),
        ),
    ]
