# Generated by Django 5.0.6 on 2024-06-06 10:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_performancemusswessels_datum_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='PerformanceMusswessels',
        ),
        migrations.RemoveField(
            model_name='todotask',
            name='assignee',
        ),
        migrations.AddField(
            model_name='todotask',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
