# Generated by Django 5.0.6 on 2024-06-06 10:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_delete_item_delete_performancemusswessels_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todotask',
            name='due_date',
            field=models.DateField(default=datetime.date(2024, 6, 6)),
        ),
    ]
