# Generated by Django 5.0.6 on 2024-06-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_todotask_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='todotask',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
