# Generated by Django 5.0.6 on 2024-06-12 09:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_todotask_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todotask',
            name='due_date',
            field=models.DateField(default=datetime.date(2024, 6, 12)),
        ),
        migrations.AlterField(
            model_name='todotask',
            name='titel',
            field=models.CharField(default='fuck you', max_length=255),
        ),
    ]
