# Generated by Django 5.0.6 on 2024-06-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_titel_todotask_title_alter_todotask_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todotask',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
