name: dodomo

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgresql:/var/lib/postgresql/data
    env_file:
      - .env

  backend:
    build:
      context: ./backend
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8001
    volumes:
      - ./backend:/app
    ports:
      - "8001:8001"
    depends_on:
      - db
    env_file:
      - ./backend/.env

volumes:
  postgres_data:
